### PR TITLE
JCLOUDS-1101: Upgrade to auto-value 1.4-rc2

### PR DESCRIPTION
**Pull request by andrewgaul**
This resolves issues using Java 9.  Release notes:

https://github.com/google/auto/releases/tag/auto-value-1.4-rc2

### CODE REVIEW

**Comment by nacx** [comment]
Thanks @andrewgaul!
Are there required changes in the labs repos?

**Comment by andrewgaul** [comment]
Seems like everything has `<scope>provided</scope>`.

**Comment by nacx** [comment]
I meant code changes like the removed builder constructors.

**Comment by andrewgaul** [comment]
Verified that labs, karaf, and cli compile with this commit.

**Comment by nacx** [comment]
Cool! :D It's great to see we are more JDK 9 friendly. Thanks for taking care of this!

**Pull request merged**
