### PR TITLE
Using a custom ConnectorFactory for ssh-agent that only tries netcat

### PR DESCRIPTION
**Pull request by demobox**
See http://markmail.org/thread/oto47qk2kzcdtebb

### CODE REVIEW

**Comment by demobox** [comment]
Comment from @nacx: "I've built your branch and I've been able to list nodes without issues (in OSX)." Now to find out what the build problem is...

**Comment by demobox** [comment]
Looks like a Jenkins issue - let's try this again...

**Comment by nacx** [comment]
I assume the same fix has to be applied to the [jsch driver](https://github.com/jclouds/jclouds/blob/master/drivers/jsch/src/main/java/org/jclouds/ssh/jsch/config/JschSshClientModule.java#L55-L61)?

**Comment by demobox** [comment]
> I assume the same fix has to be applied to the jsch driver?

Not yet...testing this one first. Good point! ;-)

**Comment by demobox** [comment]
> Failed — Merged build finished.

Another Jenkins error, by the looks of things? Just cleared the workspace.

**Comment by demobox** [comment]
> All is well — Merged build finished.

Phew ;-)

**Comment by demobox** [comment]
@nacx: Just to be sure...is this OK for you?

**Comment by nacx** [comment]
Yes! :) Thanks for taking care of this!

**Comment by demobox** [comment]
Merged to [master](https://git-wip-us.apache.org/repos/asf?p=jclouds.git;a=search;s=Andrew+Phillips;st=author).

@nacx: Also backport to 1.9.x?

**Comment by nacx** [comment]
Yep, I'd backport it too. Thanks @demobox!

**Comment by demobox** [comment]
Backported to [1.9.x](https://git-wip-us.apache.org/repos/asf?p=jclouds.git;h=0e2ee14)

**Pull request closed without merging**
