### PR TITLE
JCLOUDS-872: Swift copy object and append metadata

### PR DESCRIPTION
**Pull request by andrewgaul**
The existing method replaces metadata.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@zack-shoylev Follow on to #840.  I added some live tests but running `mvn integration-test -pl :rackspace-cloudfiles-us` does not seem to run tests from `ObjectApiLiveTest`.  Does the `rackspace-cloudfiles-us` provider need to subclass this class?

**Comment by zack-shoylev** [comment]
It seems the two providers are not extending the features tests from rackspace-cloudfiles, which is why you are seeing this.

We should just extend all of these to the providers, instead of testing them separately (hassle). It might make sense to directly extend from swift where applicable.

-Zack

________________________________

**Comment by andrewgaul** [comment]
Subclasses `ObjectApiLiveTest` in #843.  We can address other classes in subsequent commits.

**Comment by andrewgaul** [comment]
rebuild please

**Pull request merged**
