### PR TITLE
create java-xmlbuilder.version property for maven

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by nacx** [comment]
+1

**Comment by nacx** [comment]
Should it be better, though to add the dependency to the `dependencyManagement` version so the downstream projects don't even have to specify the version?

**Comment by andreaturli** [comment]
+1, I'll address this comment and update https://github.com/jclouds/jclouds-labs/pull/180 as well

**Comment by andrewgaul** [comment]
Just FYI I suggested removing java-xmlbuilder in [JCLOUDS-821](https://issues.apache.org/jira/browse/JCLOUDS-821).

**Comment by andreaturli** [comment]
thanks @nacx, addressed comments, rebased and squashed.
If the builder is happy, I'll merge it onto master and 1.9.x. Ok?

**Comment by andreaturli** [comment]
@andrewgaul I think `azurecompute` in labs uses it quite a lot. Do we want to keep JCLOUDS-821 opened anyway?

**Comment by andreaturli** [comment]
@andrewgaul, @nacx is there anything else I need to do to before merging with 1.9.1-SNAPSHOT as well as 2.0.0-SNAPSHOT? Thanks!

**Comment by andrewgaul** [comment]
:+1:

**Comment by nacx** [comment]
+1!

**Comment by andreaturli** [comment]
Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/61b06329) and [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/0aad1387)

**Comment by andreaturli** [comment]
thanks guys!

**Pull request closed without merging**
