### PR TITLE
Improve Jetty installation for live tests

### PR DESCRIPTION
**Pull request by andreaturli**
Notice `sudo` shouldn't be a problem as `AdminAccess` will add the `web` user to sudoers

Fixes a failing test with `BaseComputeServiceLiveTest.testCreateAndRunAService` on a `CentOS 7.x` image

### CODE REVIEW

**Comment by nacx** [comment]
Closing and re-opening to test new PR build

**Comment by nacx** [comment]
@andreaturli Any chance you can use this branch to upgrade Jetty to fix the vulnerability?

**Comment by andreaturli** [comment]
thanks @nacx I've bumped the jetty version to the latest `9.4.12.v20180830`

**Comment by nacx** [comment]
Looks like the version with the fix require Java 8: https://www.eclipse.org/lists/jetty-announce/msg00080.html
Let's revert this and file a proper JIRA issue to track the Jetty thing. It's not a critical thing, as the Jetty statement is mostly used just for tests.

**Comment by gaul** [comment]
Please reopen against apache/jclouds if this is still relevant.

**Pull request closed without merging**
