### PR TITLE
Replace legacy cloudfiles with modern rackspace-cloudfiles

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by andrewgaul** [comment]
:+1:

**Comment by zack-shoylev** [comment]
merged, backported

**Comment by nacx** [comment]
Out of curiosity, when should the legacy cloudfiles api be removed? Sounds reasonable to remove it for 2.0.0?

**Comment by zack-shoylev** [comment]
nacx: yes

**Comment by andrewgaul** [comment]
@nacx @ccustine We need to port HP Cloud Object Storage from legacy to modern swift before removing the legacy provider.

**Pull request closed without merging**
