### PR TITLE
JCLOUDS-1362: Better password generation utility

### PR DESCRIPTION
**Pull request by nacx**

### CODE REVIEW

**Comment by nacx** [comment]
The failure looks like a Jenkins internal issue; rebuild, please!

**Comment by nacx** [comment]
The failure looks like a Jenkins internal issue; rebuild please!

**Comment by nacx** [comment]
Pushed to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/9fef6ed0) and [2.0.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/22209966).

**Comment by neykov** [comment]
Nice change, LGTM.

**Pull request closed without merging**
