### PR TITLE
Update field address type to Href and update tests templates

### PR DESCRIPTION
**Pull request by cpanato**
Packet.net change the facilities api response and the address have a Href field now.

this try to fixes the issues we observed when using the jclouds-plugin for jenkins

### CODE REVIEW

**Comment by andreaturli** [comment]
thanks @cpanato! Glad to know you guys are using (and fixing) packet.net provider

Please keep up with the great work, merging now!

**Comment by andreaturli** [comment]
Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/e153322e)

**Comment by nacx** [comment]
Thanks! @andreaturli worth amending and cherry-picking to the 2.0.x branch in the jclouds-labs repo?

**Comment by andreaturli** [comment]
good question @nacx I'll try to apply it to jclouds-labs 2.0.x as well

**Comment by andreaturli** [comment]
merged at [jclouds-labs/2.0.x](http://git-wip-us.apache.org/repos/asf/jclouds-labs/commit/e4e8da3a) too

**Comment by cpanato** [comment]
@andreaturli can I build the jcloud-plugin using this commit you did to 2.0.x ?

**Comment by cpanato** [comment]
is it possible release or how can I use that?

**Comment by andreaturli** [comment]
I think you can build `jclouds-plugin` using that commit or you can use daily builds as described at http://jclouds.apache.org/start/install/. HTH

**Comment by nacx** [comment]
@cpanato do you mean the Jenkins plugin? We don't control it so you'd better talk to them for questions about the next release. They're very kind and release quite often :) If not, having a build from the latest snapshot is pretty straightforward. (/cc @felfert)

**Comment by cpanato** [comment]
@nacx yes the jenkins-plugin :) thanks!
I tried to compile but no success to get the jcloud-labs snapshot :/. will try again.

**Comment by nacx** [comment]
Did you configure the Apache snapshots repo mentioned in Andrea's link? Perhaps the jars were not yet published.This is the build that publishes them and has passed so all should be in place: https://jclouds.ci.cloudbees.com/job/jclouds-labs-2.0.x-branch/
Could you try again?

**Comment by cpanato** [comment]
@nacx thanks for the reply. I tried this:

changed the pom.xml in the jclouds-plugin to : 
`<jclouds.version>2.1.0-SNAPSHOT</jclouds.version>`

and added:
```
<repository>
        <id>jclouds-snapshots</id>
        <url>https://repository.apache.org/content/repositories/snapshots</url>
        <snapshots>
            <enabled>true</enabled>
        </snapshots>
    </repository>
``` 

when compiling got this error:

```
[INFO] -------------------------------------------------------------
[ERROR] COMPILATION ERROR :
[INFO] -------------------------------------------------------------
[ERROR] /Users/cpanato/project/jcloud/jclouds-plugin/jclouds-plugin/src/main/java/org/jclouds/googlecomputeengine/compute/GoogleComputeEngineServiceAdapter.java:[141,33] no suitable constructor found for Builder(java.lang.String,java.net.URI,java.net.URI,java.util.List<org.jclouds.googlecomputeengine.domain.AttachDisk>)
    constructor org.jclouds.googlecomputeengine.domain.NewInstance.Builder.Builder(java.lang.String,java.net.URI,java.net.URI,java.net.URI,java.util.List<org.jclouds.googlecomputeengine.domain.AttachDisk>) is not applicable
      (actual and formal argument lists differ in length)
    constructor org.jclouds.googlecomputeengine.domain.NewInstance.Builder.Builder(java.lang.String,java.net.URI,java.net.URI,java.net.URI,java.net.URI) is not applicable
      (actual and formal argument lists differ in length)
[INFO] 1 error
[INFO] -------------------------------------------------------------
[INFO] ------------------------------------------------------------------------
[INFO] Reactor Summary:
[INFO]
[INFO] Jenkins JClouds plugin parent POM .................. SUCCESS [  8.000 s]
[INFO] jclouds shaded jar for Jenkins plugin .............. SUCCESS [ 10.738 s]
[INFO] Jenkins JClouds plugin ............................. FAILURE [ 17.882 s]
[INFO] ------------------------------------------------------------------------
```

**Comment by cpanato** [comment]
ok sorry for the popcorn, was me doing wrong things in mvn :)

**Comment by cpanato** [comment]
working like a charm now :D 

thanks @nacx @andreaturli

**Comment by nacx** [comment]
Great! :) And thanks for the patch!

**Pull request closed without merging**
