### PR TITLE
JCLOUDS-1333: Fix Java 8 and Guava 21 issues

### PR DESCRIPTION
**Pull request by gaul**

### CODE REVIEW

**Comment by nacx** [comment]
Thanks for taking a look at this, @gaul! Build is failing for me:

```bash
$ mvn -version
Apache Maven 3.2.5 (12a6b3acb947671f09b81f49094c53f426d8cea1; 2014-12-14T18:29:23+01:00)
Maven home: /opt/maven
Java version: 1.8.0_162, vendor: Oracle Corporation
Java home: /usr/java/jdk1.8.0_162/jre
Default locale: en_US, platform encoding: UTF-8
OS name: "linux", version: "4.15.12-301.fc27.x86_64", arch: "amd64", family: "unix"

$ mvn clean install -Dguava.version=21.0 -pl core
[INFO] Scanning for projects...
[INFO]                                                                         
[INFO] ------------------------------------------------------------------------
[INFO] Building jclouds Components Core 2.2.0-SNAPSHOT
[INFO] ------------------------------------------------------------------------
[INFO] 
[INFO] --- maven-clean-plugin:2.5:clean (default-clean) @ jclouds-core ---
[INFO] Deleting /home/ibarrera/src/asf/jclouds/core/target
[INFO] 
[INFO] --- maven-enforcer-plugin:1.1.1:enforce (enforce-banned-dependencies) @ jclouds-core ---
[INFO] 
[INFO] --- maven-enforcer-plugin:1.1.1:enforce (enforce-java) @ jclouds-core ---
[INFO] 
[INFO] --- maven-remote-resources-plugin:1.5:process (default) @ jclouds-core ---
[INFO] 
[INFO] --- maven-resources-plugin:2.6:resources (default-resources) @ jclouds-core ---
[INFO] Using 'UTF-8' encoding to copy filtered resources.
[INFO] skip non existing resourceDirectory /home/ibarrera/src/asf/jclouds/core/src/main/resources
[INFO] skip non existing resourceDirectory /home/ibarrera/src/asf/jclouds/core/target/classes
[INFO] Copying 3 resources
[INFO] 
[INFO] --- maven-compiler-plugin:3.1:compile (default-compile) @ jclouds-core ---
[INFO] Changes detected - recompiling the module!
[INFO] Compiling 358 source files to /home/ibarrera/src/asf/jclouds/core/target/classes
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:199: error: <anonymous org.jclouds.reflect.Reflection2$5$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> constructor = tryFind(constructors, new Predicate<Invokable<?, ?>>() {
                                                                                                              ^
/home/ibarrera/src/asf/jclouds/core/src/main/java/org/jclouds/reflect/Reflection2.java:267: error: <anonymous org.jclouds.reflect.Reflection2$7$1> is not abstract and does not override abstract method test(Invokable<?,?>) in Predicate
               Optional<Invokable<?, ?>> method = tryFind(methods, new Predicate<Invokable<?, ?>>() {
                                                                                                    ^
Note: Some input files use or override a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
2 errors
[INFO] ------------------------------------------------------------------------
[INFO] BUILD FAILURE
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 4.663 s
[INFO] Finished at: 2018-04-09T08:30:37+02:00
[INFO] Final Memory: 80M/661M
[INFO] ------------------------------------------------------------------------
```

**Comment by gaul** [comment]
> Thanks for taking a look at this, @gaul! Build is failing for me:

You need to set `maven.compile.source` and `maven.compile.target` to 1.8 to compile with Guava 21.

**Comment by nacx** [comment]
>You need to set maven.compile.source and maven.compile.target to 1.8 to compile with Guava 21.

Right. I forgot :) Now build works with: `mvn clean install -Dguaca.version=21.0 -Dmaven.compile.source=1.8 -Dmaven.compile.target=1.8 -Danimal.sniffer.skip -Dmodernizer.skip`

I haven't spend time looking at the modernizer violations but I guess we'll have to address them once we officially support Java 8 as our default version and we change the defaults for the compile source/target.

**Comment by andreaturli** [comment]
FYI using the same @nacx's mvn command I get
```
[INFO] ------------------------------------------------------------------------
[INFO] BUILD SUCCESS
[INFO] ------------------------------------------------------------------------
[INFO] Total time: 10:00 min
[INFO] Finished at: 2018-04-10T11:12:55+02:00
```
Thanks @gaul

**Comment by gaul** [comment]
> I haven't spend time looking at the modernizer violations but I guess we'll have to address them once we officially support Java 8 as our default version and we change the defaults for the compile source/target.

Agree that we have more work to do here and this is the first step.  Could you set up another matrix build for Java 8 and Guava 21?

**Comment by nacx** [comment]
Done. I've updated the matrix build to force the compile source and target and added Guava 21.0. If I've not messed it up, the Guava 21 build should be skipped for Java 1.7.

**Comment by demobox** [comment]
Thanks for taking this on, @gaul and @nacx! Java 8 here we finally come... ;-)

**Pull request merged**
