### PR TITLE
JCLOUDS-1161: Make AWSS3BlobRequestSignerV4 the default signer.

### PR DESCRIPTION
**Pull request by shrinandj**
Fix unit tests accordingly.

### CODE REVIEW

**Comment by andrewgaul** [comment]
Does this address any particular issue, e.g., using signed requests in eu-central-1 region?  If so, please include an integration test.

**Comment by shrinandj** [comment]
Added a new live test, specifically run against eu-central-1 region.

**Comment by andrewgaul** [comment]
Tests show the following errors:

```
$ mvn integration-test -pl :aws-s3 -Plive -Dtest.aws-s3.identity="${JCLOUDS_IDENTITY}" -Dtest.aws-s3.credential="${JCLOUDS_CREDENTIAL}" -Dtest=AWSS3BlobSignerLiveTest
...
Failed tests: 
  AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignGetUrlWithTime:39->BaseBlobSignerLiveTest.testSignGetUrlWithTime:92->BaseBlobStoreIntegrationTest.assertConsistencyAwareContainerSize:311->BaseBlobStoreIntegrationTest.assertConsistencyAware:252->BaseBlobStoreIntegrationTest.assertConsistencyAware:239 » ContainerNotFound
  AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignPutUrlWithTime:60 null
  AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignGetUrlWithTimeExpired:49->BaseBlobSignerLiveTest.testSignGetUrlWithTimeExpired:115 » AWSResponse
  AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignPutUrlWithTimeExpired:69->BaseBlobSignerLiveTest.testSignPutUrlWithTimeExpired:179 » AWSResponse

Tests run: 8, Failures: 4, Errors: 0, Skipped: 0
```

**Comment by shrinandj** [comment]
Do the live tests run successfully on current master? The same 4 tests above failed for me on current master.

**Comment by andrewgaul** [comment]
These four tests now succeed on master.  You need to fix these two which fail with your change:

```
AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignGetUrlWithTimeExpired:55->BaseBlobSignerLiveTest.testSignGetUrlWithTimeExpired:115 » AWSResponse
AWSS3BlobSignerLiveTest>S3BlobSignerLiveTest.testSignPutUrlWithTimeExpired:79->BaseBlobSignerLiveTest.testSignPutUrlWithTimeExpired:179 » AWSResponse
```

**Comment by shrinandj** [comment]
Thanks for fixing the tests on master @andrewgaul. I am able to run the tests successfully on master and also able to reproduce the test failures with my change. I'll fix them and upload a new commit.

**Comment by ashkanpaya88** [comment]
Is this change going to be included in jclouds 2.0 ?

**Comment by andrewgaul** [comment]
Pushed to master as 7826d22d301b1a6accef2b7686700231ffba7e29.

**Comment by nacx** [comment]
>Is this change going to be included in jclouds 2.0

Yes!

**Pull request closed without merging**
