### PR TITLE
JCLOUDS-995 - Add `userData` property to `CloudStackTemplateOptions` …

### PR DESCRIPTION
**Pull request by momania**
…and map it in the underlying adapter.

### CODE REVIEW

**Comment by nacx** [comment]
Thanks @momania! lgtm. Just a minor comment: could you double-check the formatting and [use a 3 space indentation](https://cwiki.apache.org/confluence/display/JCLOUDS/Coding+Standards)?

**Comment by momania** [comment]
Sure, I'll update the pull request later today to fix that.

**Comment by momania** [comment]
@nacx Is it ok like this, or do you want me to squash it together as 1 commit?

**Comment by nacx** [comment]
It is ok. Thanks! I'll squash the commits when merging.

**Comment by nacx** [comment]
Squashed and pushed to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/89f81840) and [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/1ef5c701). Thanks @momania!

**Pull request closed without merging**
