### PR TITLE
JCLOUDS-1044 fix handling NULL JsonTokens in adapters under NullFilte…

### PR DESCRIPTION
**Pull request by duncangrant**
…ringTypeAdapterFactories class

This PR backports this fix (0fb1b459a607f21f6a8ebd7492879d02553c4b88) from 2.0.0 to 1.9.x.

### CODE REVIEW

**Comment by grkvlt** [comment]
@andreaturli Can you take a look, please? We need this for the jclouds-labs Docker provider, to fix behaviour where JSON maps returned by the Docker REST API have entries with null values, instead of empty lists.

**Comment by nacx** [comment]
LGTM! Let's merge it once the build finishes and is green. Thanks @duncangrant @grkvlt!

**Comment by duncangrant** [comment]
@nacx thanks

**Comment by andreaturli** [comment]
Sorry @grkvlt I've been notified just now about this PR by github, looks like @nacx already reviewed it: thanks @nacx !

**Comment by andreaturli** [comment]
ok build is happy, merging now

**Comment by andreaturli** [comment]
Merged at [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/7016b040)

**Comment by andreaturli** [comment]
thanks @duncangrant

**Pull request closed without merging**
