### PR TITLE
support aliyun oss and chinese region of aws s3 on jclouds 1.9.1

### PR DESCRIPTION
**Pull request by xingyunyang**
https://issues.apache.org/jira/projects/JCLOUDS/issues/JCLOUDS-1471?filter=reportedbyme

The pre-version's jclouds code, we find it not support aliyun oss and chinese region of aws s3, so we add code for these features on 1.9.1.

### CODE REVIEW

**Comment by nacx** [comment]
It is _very_ unlikely that we release another 1.9 version, so I'd suggest you open the pull request to the master branch, then we can cherry-pick it to 2.1.x.

This said, there are things that are fundaamentally wrong in this pull request such as hardcoding endpoint logic in jclouds-core (RestAnnotationProcessor for example) that need to be changed and redesigned in order for the PR to be mergeable.

I'll be happy to give advice and guidance if you drop an email to the jclouds dev@ list describing the use case and the fix that needs to be done. Then we'll be able to point you to the proper way of getting it done.

**Comment by xingyunyang** [comment]
Hello, lgnasi:

 

     It is happy to receive your email.Accoding your describe, I check my code, but I don’t know how to fix.

 

     The purpose of our code is to achieve two things:

1.       Add aliyun object storage function(public cloud and private cloud). Aliyun is a subsidiary of Chinese company Alibaba, it provides cloud service. A lot of Chinese people use it. The SDK of aliyun object storage is compatible with AWS S3, except for the signature authentication. Therefore, our developers are imitating jclouds' support for aws s3 and adding relevant code of aliyun object storage cloud. 

2.       Add aws s3 AWS S3 China(cn-north-1) support.

 

On our storage device, we've tested and passed this code. However, because our developers do not understand the structure of jclouds code, the code we write does not meet your requirements. And we also didn't find a way to do unit testing, so we didn't write unit test code.

 

Do you have any Suggestions for this situation?

 

发件人: Ignasi Barrera [mailto:notifications@github.com] 
发送时间: 2018年12月17日 10:50
收件人: jclouds/jclouds <jclouds@noreply.github.com>
抄送: Bruce Xing(邢云阳) <xingyunyang@inspur.com>; Author <author@noreply.github.com>
主题: Re: [jclouds/jclouds] support aliyun oss and chinese region of aws s3 on jclouds 1.9.1 (#1263)

 

It is very unlikely that we release another 1.9 version, so I'd suggest you open the pull request to the master branch, then we can cherry-pick it to 2.1.x.

This said, there are things that are fundaamentally wrong in this pull request such as hardcoding endpoint logic in jclouds-core (RestAnnotationProcessor for example) that need to be changed and redesigned in order for the PR to be mergeable.

I'll be happy to give advice and guidance if you drop an email to the jclouds dev@ list describing the use case and the fix that needs to be done. Then we'll be able to point you to the proper way of getting it done.

**Comment by gaul** [comment]
@xingyunyang This code has incorrect structure.  The s3 API is vendor-neutral which supports many providers by overriding the endpoint.  Please study the aws-s3 provider which extends the s3 API in the manner which you should structure your Aliyun pull request.  Also please study the unit tests for signing request which we will require for your new functionality.  Finally we require that all code merges first with master and we can evaluate backports to other branches.

**Review by gaul — CHANGES_REQUESTED** [review]
See above comment.

**Comment by gaul** [comment]
Please reopen against apache/jclouds if this is still relevant.

**Pull request closed without merging**
