### PR TITLE
disable directory blob tests in OS X

### PR DESCRIPTION
**Pull request by kahing**
On OS X, java doesn't support xattrs, which is required by
directory blobs. Disable those tests on OS X

should fix @jdaggett 's problem with #637

### CODE REVIEW

**Comment by jdaggett** [comment]
@kahing Thanks for the fix! This is exactly how I worked around the issue earlier this morning. As soon as the build succeeds, I am +1 for this PR. cc/ @andrewgaul

**Comment by andrewgaul** [comment]
Pushed to master as 5cc3b243fc878a44091b78b14d8e5cb00086a75a.

This commit addresses the test failures, although we might need a more general solution.  Unfortunately lack of extended attributes on Mac OS X is a [JDK issue](https://bugs.openjdk.java.net/browse/JDK-8030048).

**Comment by jdaggett** [comment]
@kahing @andrewgaul After pulling this commit and running the tests again, I am getting two new failures :confused: :
```
Failed tests:
  FilesystemBlobIntegrationTest>BaseBlobIntegrationTest.testPutByteSource:531->BaseBlobIntegrationTest.testPut:584
Expecting:
 <{}>
to be equal to:
 <{"key1"="value1", "key2"="value2"}>
but was not.
  FilesystemBlobIntegrationTest>BaseBlobIntegrationTest.testPutInputStream:539->BaseBlobIntegrationTest.testPut:584
Expecting:
 <{}>
to be equal to:
 <{"key1"="value1", "key2"="value2"}>
but was not.
```

Any insight is appreciated, thx!

**Comment by jdaggett** [comment]
We should skip those additional two tests as well. I will submit a PR shortly with the changes, thx!

**Pull request closed without merging**
