### PR TITLE
JCLOUDS-1225: Guava 18 changes

### PR DESCRIPTION
**Pull request by andrewgaul**

### CODE REVIEW

**Comment by demobox** [comment]
@andrewgaul Merge conflict? :-(

And just to confirm: this would now make us incompatible with Guava < 18?

**Comment by webfolderio** [comment]
Who cares Guava < 18?

Please merge it.

**Comment by andrewgaul** [comment]
> @andrewgaul Merge conflict? :-(

Hard to avoid when touching hundreds of files!

> And just to confirm: this would now make us incompatible with Guava < 18?

Previously jclouds had compatibility with Guava 16-20.  Now it will have compatibility with 18-23.

**Comment by demobox** [comment]
> Now it will have compatibility with 18-23.

Niiiice. Thanks for taking this on! +1 - looks good to go for me. I'm guessing we should be updating the [compatibility Jenkins job](https://jclouds.ci.cloudbees.com/job/jclouds-compat/), too.

@andrewgaul Would we expect this change to also fix the breaking Guava 20 compatibility builds?
```
20.0.jar(com/google/common/util/concurrent/ExecutionList.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy': class file for javax.annotation.concurrent.GuardedBy not found
/home/jenkins/.m2/repository/com/google/guava/guava/20.0/guava-20.0.jar(com/google/common/util/concurrent/ExecutionList.class): warning: Cannot find annotation method 'value()' in type 'GuardedBy'
error: cannot access CanIgnoreReturnValue
  class file for com.google.errorprone.annotations.CanIgnoreReturnValue not found
Note: Some input files use or override a deprecated API.
```

**Comment by andrewgaul** [comment]
> @andrewgaul Would we expect this change to also fix the breaking Guava 20 compatibility builds, e.g. this one?

I encountered similar errors when testing different Guava versions.  Adding `error_prone_annotations` to pom.xml fixes this.

**Comment by andrewgaul** [comment]
The compatibility builds introduce another wrinkle: this commit makes jclouds compatible with Guava 23 applications but not jclouds itself due to some Java 8 nonsense.

**Comment by andrewgaul** [comment]
Guava 20 `CanIgnoreReturnValue` errors addressed in 5e12796a34b11be7fe5183f220167bf96793b291.  I updated the compat matrix build with 18-20.  Guava 21-23 require some Java 8 hacking.

**Pull request merged**
