### PR TITLE
JCLOUDS-1160: Upgrade to Gson 2.7

### PR DESCRIPTION
**Pull request by andrewgaul**
Changelog:

https://github.com/google/gson/blob/master/CHANGELOG.md

### CODE REVIEW

**Comment by demobox** [comment]
Thanks, Andrew G! I had only checked the changelog between 2.6.2 and 2.7 - are there any transitive deps that might be affected by the jump from 2.3.1?

/cc @nacx

**Comment by nacx** [comment]
I don't think so. AFAIK we don't have dependencies that rely on gson apart form jclouds-core. I'd say the change is safe.

All mock and expect tests passing give us a lot of confidence. There are several providers (such as Chef) that use complex adapters and all tests are still passing. There are also the google auto tests, that check the sensible corner cases, so as long as all tests pass, I'd say this is good to merge.

**Comment by demobox** [comment]
> I'd say this is good to merge

Good enough for me - +1 from me too. Thanks for the additional details, Ignasi!

**Comment by andrewgaul** [comment]
gson does not have any runtime dependencies:

```
[INFO] --- maven-dependency-plugin:2.8:tree (default-cli) @ gson ---
[INFO] com.google.code.gson:gson:jar:2.7.1-SNAPSHOT
[INFO] \- junit:junit:jar:4.12:test
[INFO]    \- org.hamcrest:hamcrest-core:jar:1.3:test
```

**Comment by demobox** [comment]
> gson does not have any runtime dependencies:

Thanks for confirming, Andrew G!

**Pull request merged**
