### PR TITLE
Fix Issue with flavor creation by making links nullable

### PR DESCRIPTION
**Pull request by arvindn05**
Fix Issue with flavor creation by making links nullable
see https://issues.apache.org/jira/browse/JCLOUDS-1126

### CODE REVIEW

**Comment by zack-shoylev** [comment]
Looks good to me!

**Comment by arvindn05** [comment]
thanks Zack!

**Comment by zack-shoylev** [comment]
merged and backported

**Comment by nacx** [comment]
Can we mark the JRIA issue as resolved?

**Comment by arvindn05** [comment]
i think so for now. But the issue i created was to track a general issue with with new validations introduced as part of v2.1 of openstack api's.

This might be only the first instance of these new validations causing issues...i will reopen if i see issues in other apis.

Thanks for the quick review!

**Comment by nacx** [comment]
Will stay tuned then. Thanks for the contribution!

**Pull request closed without merging**
