### PR TITLE
Remove all sonatype snapshot repositories

### PR DESCRIPTION
**Pull request by nacx**

### CODE REVIEW

**Comment by demobox** [comment]
Thanks for the cleanup, Ignasi! +1, looks good to me.

**Comment by andrewgaul** [comment]
👍 Please backport to 2.0.x since it may address failures such as: https://travis-ci.org/andrewgaul/s3proxy/builds/207098979

**Comment by andrewgaul** [comment]
Never mind, a coincidence of errors.

**Comment by nacx** [comment]
Pushed to master as [2f70f85c](http://git-wip-us.apache.org/repos/asf/jclouds/commit/2f70f85c).

**Pull request closed without merging**
