### PR TITLE
Uses default password with conflictive characters

### PR DESCRIPTION
**Pull request by danielestevez**

### CODE REVIEW

**Comment by danielestevez** [comment]
cc @demobox

**Comment by demobox** [comment]
Thanks, Daniel!

@nacx You probably have a bit more context with regard to the overall change - does this cover the cases that were discussed in the previous PR?

**Comment by nacx** [comment]
Merged to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/bdb9a3af) and [2.1.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/45230c87). Thanks!

**Comment by demobox** [comment]
Thanks for taking care of the merging and cherry-picking, Ignasi!

**Pull request closed without merging**
