### PR TITLE
Add tag support to azure disks

### PR DESCRIPTION
**Pull request by pimuzzo**
Fix https://issues.apache.org/jira/browse/JCLOUDS-1506

### CODE REVIEW

**Comment by nacx** [comment]
Thanks, @pimuzzo! Can you add the corresponding test in the `DiskApiMockTest`? It should be as easy as copying the existing create test and checking that the payload includes the tags.

**Comment by pimuzzo** [comment]
@nacx where/when this tests run?

**Comment by nacx** [comment]
Unit (mock) tests run on every build. For live tests, which actually cost money :), we run them before a release, mostly using our accounts, so we can't afford run them all. [Some providers](https://cwiki.apache.org/confluence/display/JCLOUDS/Test+Provider+Thanks) help the project with testing accounts. We run the tests for those on every release for sure, and we have a (very) few of them [running weekly](https://builds.apache.org/view/J/view/jclouds/job/jclouds-with-credentials/).

**Comment by nacx** [comment]
Squashed and pushed to [master](https://github.com/apache/jclouds/commit/fcf72e5ea58bcbe16b25f2a12c29ca55cc7c000c) and [2.1.x](https://github.com/apache/jclouds/commit/bd59263d470f4307fe1a70a064e11c1ebeea064a). Thanks!

Please consider opening upcoming PRs on the [apache/jclouds](https://github.com/apache/jclouds) repo.

**Pull request closed without merging**
