### PR TITLE
Update cloudfiles poms

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by zack-shoylev** [comment]
Rebuild please?

**Comment by nacx** [comment]
Looks good. A couple comments:

* Should the exising `cloudfiles` providers be removed? Are they superceded by the promoted ones?
* Should the promoted ones be added to the `allblobstore` pom?

**Comment by zack-shoylev** [comment]
That would be the plan going forward, though maybe not as part of this PR. I am not sure what the right timing would be to do that, yet.

**Comment by nacx** [comment]
Do you refer to the removal of the existing cloudfiles provider, or to adding the new provides to the blobstore aggregator pom?

**Comment by zack-shoylev** [comment]
Both

**Comment by nacx** [comment]
+1 to merge it as-is then. Thanks!

What are waiting to remove the old providers? Is it something to deprecate/announce/discuss in the mailing list?

**Comment by zack-shoylev** [comment]
merged and backported

**Pull request closed without merging**
