### PR TITLE
[JCLOUDS-1233] bump jax-rs version

### PR DESCRIPTION
**Pull request by andreaturli**
/cc @nacx and @neykov

### CODE REVIEW

**Comment by neykov** [comment]
LGTM

**Comment by nacx** [comment]
Before merging let's double check there are no version conflicts int he labs projects and/or karaf/cli.

**Comment by nacx** [comment]
I've just noted that the fix version in JIRA is marked for 2.0.1, but I don't think we should upgrade libraries in bugfix versions. IMO this shouldn't be backported to 2.0.x.

**Comment by andreaturli** [comment]
agreed changed to `2.1.0`, also testing jclouds-labs-* with the new jclouds/jclouds

**Comment by andreaturli** [comment]
tested successfully `mvn clean install` with jclouds-labs, jclouds-labs-aws, jclouds-labs-google 

jclouds-labs-openstack seems to have building problems independent of that PR

**Comment by zack-shoylev** [comment]
> jclouds-labs-openstack seems to have building problems independent of that PR

I'll have a look

**Comment by andreaturli** [comment]
thanks @zack-shoylev my fork was not in sync, sorry about that

**Comment by andreaturli** [comment]
@nacx, both @zack-shoylev and myself tested this change and it looks fine. Good to merge?

**Comment by andreaturli** [comment]
thanks @nacx -- do you think it is just for master or also 2.0.x?

**Comment by andreaturli** [comment]
merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/38cb34e1)

**Comment by nacx** [comment]
Just for master. We don't want to introduce dependency conflicts in people upgrading to 2.0.1.

**Comment by andreaturli** [comment]
k thx

**Comment by nacx** [comment]
Looks like this has broken jclouds-karaf:
https://jclouds.ci.cloudbees.com/job/jclouds-karaf/org.apache.jclouds.karaf$itests/2088/

    features:install jclouds-rackspace-cloudfiles-us
    java.lang.Exception: Could not start bundle mvn:org.apache.jclouds/jclouds-core/2.1.0-SNAPSHOT in feature(s) jclouds-2.1.0-SNAPSHOT: Unresolved constraint in bundle jclouds-core [83]: Unable to resolve 83.0: missing requirement [83.0] osgi.wiring.package; (&(osgi.wiring.package=javax.ws.rs)(version>=2.0.0)(!(version>=3.0.0)))

**Comment by jclouds-mirror** [comment]
I'm sure https://github.com/jclouds/jclouds-karaf/pull/92 fixes it but I
will extract it from that PR and submit asap a patch

**Pull request closed without merging**
