### PR TITLE
OAuth filter customization per request

### PR DESCRIPTION
**Pull request by nacx**
This pull request enables a per-request customization of the OAuth properties, such as the audience and resource. This is useful for providers that have APIs that authorize different resources, such as Azure ARM and the KeyVault API.

The changes in this PR are backward-compatible and by default preserve the current behavior.

/cc @jmspring

### CODE REVIEW

**Comment by andreaturli** [comment]
I'd like to test this with arm and gce as well. I'll report on this thread asap

**Comment by andreaturli** [comment]
from slack conversation, I understand @nacx already tested this with GCE, so lgtm!

**Comment by andreaturli** [comment]
thanks @nacx !

**Comment by jmspring** [comment]
I’ll update my code this morning if there are any changes and can run the ARM tests and get back in a bit.

**Comment by jmspring** [comment]
LGTM. Some test failures I was seeing, wholly unrelated and will retest those and open issues accordingly.

**Comment by nacx** [comment]
Merged to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/624367df) and [2.0.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/3bdc25c3).

**Pull request closed without merging**
