### PR TITLE
Fix filesystem api in OSX

### PR DESCRIPTION
**Pull request by nacx**
/cc @andrewgaul @kahing

### CODE REVIEW

**Comment by demobox** [comment]
@nacx Were both of these commits intended to be part of this PR? It looks like only one small change is actually about OS X filesystem support?

**Comment by nacx** [comment]
For some reason the github PR preview shows both commits when the PR was actually rebased to the latest master. Look at the commit hash of the ec2 fix (whcih comes from a previous PR); it matches the commit that was currently on master.

The pr did actually contain only 1 commit, but the github preview showed both. Don't know why. The master commit history looks clean too.

**Comment by demobox** [comment]
> The master commit history looks clean too.

I'm sure all is well there ;-) Just wanted to check that the relevant bit of the change is indeed only:
```
-            if (!view.list().isEmpty()) {
+            if (view == null) { // OSX HFS+ does not support UserDefinedFileAttributeView
+                logger.debug("Could not look for attributes from %s", directory);
+            } else if (!view.list().isEmpty()) {
```

Regarding that: what's our feeling on making `logger.debug` calls that are not wrapped by `logger.isDebugEnabled`?

**Comment by nacx** [comment]
>Regarding that: what's our feeling on making logger.debug calls that are not wrapped by logger.isDebugEnabled?

The [jclouds loggers](https://github.com/jclouds/jclouds/blob/master/core/src/main/java/org/jclouds/logging/BaseLogger.java#L47-L50) already take care of that.

**Comment by demobox** [comment]
> The jclouds loggers already take care of that.

Er...ah, yes, of course - this is _jclouds_ logging, not SLF4J. Doh! ;-)

Thanks, Ignasi!

**Comment by nacx** [comment]
jclouds FTW! ^^

**Comment by kahing** [comment]
:+1:

**Pull request merged**
