### PR TITLE
JCLOUDS-691: Remove 404 fallbacks of PUT and POST calls from OpenStac…

### PR DESCRIPTION
**Pull request by devcsrj**
…k Apis

openstack cinder, keystone, nova, nova-ec2, swift, trove

### CODE REVIEW

**Comment by zack-shoylev** [comment]
+1

Just a note, we shouldn't be back-porting this (obviously). But it should roll out with v2.

**Comment by nacx** [comment]
This is great. Thanks @devcsrj!
Just one comment: remove all tests that verify the propagated exceptions. It is the jclouds default behavior (not anything introduced by these APIs) so we shouldn't test this. That is already tested in jclouds-core.

**Comment by devcsrj** [comment]
Just to be clear, does this mean that tests like [this](https://github.com/jclouds/jclouds/pull/911/files#diff-346bc00a46231f33755b2d3ec420cfbbR129) are no longer needed? Since the `ResourceNotFoundException` is a Fallback in the jclouds-core?

**Comment by nacx** [comment]
Exactly. It is jclouds-core the one that throws the exception in the absence of a fallback. We shouldn't test that, as if at some point we change the default behavior we could end up having to update hundreds of tests in every provider.
Let's avoid re-testing core behavior in concrete providers.

**Comment by devcsrj** [comment]
Removed *unneeded* tests, mostly checking `AuthorizationException`s and `ResourceNotFoundException`s. Please do tell if I went overboard (2,515 deletions).

**Comment by nacx** [comment]
LGTM Thanks! Mind squashing the commits before we merge the PR?

**Comment by nacx** [comment]
I'll merge this in short. For completeness, could you also apply the fix to the apis in the `jclouds-labs-openstack` repo?

**Comment by nacx** [comment]
Pushed to master as [d83282ca](http://git-wip-us.apache.org/repos/asf/jclouds/commit/d83282ca). Thanks!

**Pull request closed without merging**
