### PR TITLE
[1.9.x] update CloudstackTemplateOptions pattern

### PR DESCRIPTION
**Pull request by andreaturli**

### CODE REVIEW

**Comment by andreaturli** [comment]
I think this is a straightforward improvements to the CloudstackTemplateOptions to be in line with the other `*TemplateOptions` which we also tested in a real env. 
@nacx good to merge?

**Comment by nacx** [comment]
+1

**Comment by nacx** [comment]
Pushed to master as [a1f6b7eb](http://git-wip-us.apache.org/repos/asf/jclouds/commit/a1f6b7eb).

**Comment by andreaturli** [comment]
thx @nacx

**Pull request closed without merging**
