### PR TITLE
Token based authentication in openstack-keystone

### PR DESCRIPTION
**Pull request by pimenas**
This PR adds support for token based authentication in openstack-keystone. 

Currently openstack-keystone only supports authentication against keystone service using only username and password credentials, using the following rest request 

```
{
    "auth": {
        "tenantName": "demo",
        "passwordCredentials": {
            "username": "demo",
            "password": "devstack"
        }
    }
}
```

This PR adds support for using token based authentication which is translated to the following request to keystone:

```
{
    "auth": {
        "tenantName": "demo",
        "token": {
            "id": "cbc36478b0bd8e67e89469c7749d4127"
        }
    }
}
```

In order to use this new authentication scheme one must override the CREDENTIAL_TYPE property and set it to the new value TOKEN_CREDENTIALS. Here's some sample code

```
            // get authtoken from authentication service
            Properties overrides = new Properties();
            overrides.put(CREDENTIAL_TYPE, TOKEN_CREDENTIALS);

            Set<Module> modules = ImmutableSet.<Module> of(
                    new org.jclouds.logging.slf4j.config.SLF4JLoggingModule(),
                    new org.jclouds.sshj.config.SshjSshClientModule()); 

            ComputeServiceContext computeServiceContext = ContextBuilder.newBuilder(provider)
                .endpoint(endpoint).credentials(tenant + ":" + username, authToken)
                .overrides(overrides)
                .modules(modules)
                .buildView(ComputeServiceContext.class);

```

All you have to do in this case, is instead of supplying a password as a second argument to the `credentials()` method, you supply an authentication token that you have previously acquired.

### CODE REVIEW

**Comment by everett-toews** [comment]
Thanks for the pull request but it's release week in jclouds and that means it's time to clean up the PR queue. This PR will be over 6 months old as of April 1. If you intend to continue work on it, please make a comment by April 2. Otherwise it will be closed on April 3.

**Comment by pimenas** [comment]
I'll work on it.

**Comment by andrewgaul** [comment]
@pimenas do we have a path forward on this pull request?

**Comment by pimenas** [comment]
@gaul I'll check it during the weekend!

**Comment by nacx** [comment]
Apologies for the huge delay @pimenas . The original reviewers are not active in the project and the PR got unattended.
The changes LGTM. @andreaturli Mind having a look? If you approve the changes I'll merge the PR.

**Comment by gaul** [comment]
@pimenas Closing this due to inactivity; please reopen if you want to continue working on it.

**Pull request closed without merging**
