### PR TITLE
JCLOUDS-1381: Fix NPE in GCE DiskURIToImage

### PR DESCRIPTION
**Pull request by nacx**
https://issues.apache.org/jira/browse/JCLOUDS-1381
/cc @aledsage

### CODE REVIEW

**Comment by andreaturli** [comment]
lgtm

**Comment by nacx** [comment]
Merged to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/7aed4bc8) and [2.0.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/06e10864).

**Comment by demobox** [comment]
Is there a test we should have for this?

**Comment by nacx** [comment]
Absolutely: https://github.com/jclouds/jclouds/pull/1183

**Pull request closed without merging**
