### PR TITLE
JCLOUDS-893: Support compute API extension "Servers with scheduler hints"

### PR DESCRIPTION
**Pull request by VRanga000**
https://issues.apache.org/jira/browse/JCLOUDS-893

### CODE REVIEW

**Comment by andrewgaul** [comment]
@VRanga000 Do we have a path forward on this?

**Comment by VRanga000** [comment]
This got dropped for a while - basically there is some test (mock) code to be redone and some formatting. I will address them shortly, hopefully.

**Comment by gaul** [comment]
@VRanga000 Closing this due to inactivity; please reopen if you want to continue working on it.

**Comment by kthare10** [comment]
Would this be supported in Jclouds?

**Comment by nacx** [comment]
This has been closed but not merged. We would be happy to include this if someone continues the work and contributes it!

**Pull request closed without merging**
