### PR TITLE
Change line endings on files recursively

### PR DESCRIPTION
**Pull request by andreaturli**
This should avoid to see changes right after cloning the project

If ok, I'd like it backported to 1.9.x

### CODE REVIEW

**Comment by andrewgaul** [comment]
:+1: to UNIX line endings in XML files; the Windows batch scripts might need DOS line endings.

**Comment by andreaturli** [comment]
Thx @andrewgaul I think .gitattributes file handles `.cmd` files correctly

**Comment by nacx** [comment]
+1!

**Comment by andreaturli** [comment]
Merged at [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/a515ce2f) and backported at [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/c10d7a65)

**Pull request closed without merging**
