### PR TITLE
Handle IOException for XATTRS when reading blob on Docker

### PR DESCRIPTION
**Pull request by geertvanheusden**
PR for https://issues.apache.org/jira/browse/JCLOUDS-1218 & https://github.com/andrewgaul/s3proxy/issues/155

### CODE REVIEW

**Comment by geertvanheusden** [comment]
Not sure if https://github.com/geertvanheusden/jclouds/blob/master/apis/filesystem/src/main/java/org/jclouds/filesystem/strategy/internal/FilesystemStorageStrategyImpl.java#L689 should be handled as well? 
Is it necessary to have an XATTR_CONTENT_MD5 attribute if you want to check if the BLOB exists?

**Comment by zack-shoylev** [comment]
It seems XATTR_CONTENT_MD5 should be handled as well, but I am not very sure what's going on with how it's used.

**Comment by geertvanheusden** [comment]
@zack-shoylev any actions expected from my side before this can be merged?

**Comment by zack-shoylev** [comment]
rebuild please

**Comment by zack-shoylev** [comment]
@geertvanheusden The commits will have to be squashed, at least.

**Comment by andrewgaul** [comment]
Fixed whitespace, reworded commit message, and pushed to master as fbf62437c7e776422288564c419dc037dbd72dfa and 2.0.x as f210283cacf5a36e9d5cc303523f5730b95aae39.  Thank you for your contribution @geertvanheusden!

**Pull request closed without merging**
