### PR TITLE
Fix autovalue class loading in karaf

### PR DESCRIPTION
**Pull request by duncangrant**
When Class.forName is called for a class in a different bundle it will
fail as the default karaf class loader won't load classes from other
bundles.

I have fixed this by using the classloader of the original
(non-autovalue) type and assuming it will be in the same bundle as the
autovalue type (I think this is a reasonable assumtion).

So far the only place where I've actually seen this being an issue is
when using the jclouds-labs-google provider within karaf. It fails
when serialising the Firewall.Rule class within a FirewallOptions
object.

### CODE REVIEW

**Comment by duncangrant** [comment]
https://issues.apache.org/jira/browse/JCLOUDS-1171

**Comment by nacx** [comment]
Thanks @duncangrant! A quick search shows that this is the only place where `Class.forName` is used, and other uses of `getClassLoader()` seem legit. I'll let the CI build complete and merge the PR.

**Comment by duncangrant** [comment]
@nacx Thanks.  Should I create a PR to port this to 1.9.x?

**Comment by nacx** [comment]
>Should I create a PR to port this to 1.9.x?

Not needed. I'll take care of merging and cherry-picking  :)

**Comment by nacx** [comment]
Pushed to [master](http://git-wip-us.apache.org/repos/asf/jclouds/commit/7aad5997) and [1.9.x](http://git-wip-us.apache.org/repos/asf/jclouds/commit/c79b2355). Thanks @duncangrant!

**Pull request closed without merging**
