### PR TITLE
Promote rackspace cloudfiles 7

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by zack-shoylev** [comment]
@nacx wdyt

**Comment by nacx** [comment]
This looks good. Great job @zack-shoylev!
Mind adding the process you used to the wiki, generalizing it, if possible?

**Comment by zack-shoylev** [comment]
@nacx Alright, will do; This also works on windows (I tested that yesterday), so it's a nice bonus.

**Comment by zack-shoylev** [comment]
@nacx do you mind testing merging this?

**Comment by zack-shoylev** [comment]
merged

**Pull request closed without merging**
