### PR TITLE
JCLOUDS-979: Fix range get for LocalBlobStore

### PR DESCRIPTION
**Pull request by rcoedo**

### CODE REVIEW

**Comment by rcoedo** [comment]
Tests and style pass on my machine, am I missing something?

**Comment by zack-shoylev** [comment]
Seemed like a jenkins problem to me.

**Comment by zack-shoylev** [comment]
Looks good to me!

**Comment by andrewgaul** [comment]
:+1: Uses unbounded memory for the jdbc blobstore but we can fix this up later.

**Comment by zack-shoylev** [comment]
This should be good to merge, but I guess a backport will be needed as well?

**Comment by andrewgaul** [comment]
We can skip backporting since JDBC blobstore does not exist in 1.9.x and I did not backport the original memory saving patch for range gets.

**Pull request merged**
