### PR TITLE
Adds additional details to the jclouds log error message.

### PR DESCRIPTION
**Pull request by zack-shoylev**

### CODE REVIEW

**Comment by nacx** [comment]
Looks like an unrelated failure. rebuild please.

**Comment by zack-shoylev** [comment]
Yep, seemed alright but I reopened the PR just in case.

**Comment by nacx** [comment]
@zack-shoylev hint: with the new builds now you can just say "rebuild please" in a comment and a new build will be triggered. No need to reopen the PR :)

**Comment by zack-shoylev** [comment]
merged

**Pull request closed without merging**
