### PR TITLE
JCLOUDS-1295: Support deprecated date formats in the Expires header

### PR DESCRIPTION
**Pull request by nacx**
https://issues.apache.org/jira/browse/JCLOUDS-1295

@neykov Mind trying Azure ARM with this fix?

### CODE REVIEW

**Comment by neykov** [comment]
@nacx there's no change, the fallback fails to parse the header value which is `-1`.

I captured the traffic with wireshark and indeed the value is `-1`, contrary to what the headers log show. Here's the wireshark capture:

```
HTTP/1.1 200 OK
Cache-Control: no-cache
Pragma: no-cache
Content-Type: application/json; charset=utf-8
Content-Encoding: gzip
Expires: -1
Vary: Accept-Encoding
x-ms-ratelimit-remaining-subscription-reads: 14998
x-ms-request-id: f6cce7d2-63df-4d29-b03c-c4858e10a8ee
x-ms-correlation-request-id: f6cce7d2-63df-4d29-b03c-c4858e10a8ee
x-ms-routing-request-id: WESTEUROPE:20170529T124513Z:f6cce7d2-63df-4d29-b03c-c4858e10a8ee
Strict-Transport-Security: max-age=31536000; includeSubDomains
Date: Mon, 29 May 2017 12:45:13 GMT
Content-Length: 1850
```

And the headers log:

```
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << HTTP/1.1 200 OK
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << Date: Mon, 29 May 2017 12:45:13 GMT
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << OkHttp-Received-Millis: 1496061913957
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << OkHttp-Selected-Protocol: http/1.1
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << OkHttp-Sent-Millis: 1496061913849
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << Pragma: no-cache
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << Strict-Transport-Security: max-age=31536000; includeSubDomains
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << Vary: Accept-Encoding
2017-05-29 15:45:13,958 DEBUG 107 j.headers [ager-DOccEjYP-24] << x-ms-correlation-request-id: f6cce7d2-63df-4d29-b03c-c4858e10a8ee
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << x-ms-ratelimit-remaining-subscription-reads: 14998
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << x-ms-request-id: f6cce7d2-63df-4d29-b03c-c4858e10a8ee
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << x-ms-routing-request-id: WESTEUROPE:20170529T124513Z:f6cce7d2-63df-4d29-b03c-c4858e10a8ee
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << Cache-Control: no-cache
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << Content-Type: application/json; charset=utf-8
2017-05-29 15:45:13,959 DEBUG 107 j.headers [ager-DOccEjYP-24] << Expires: Thu Jan 01 02:00:00 EET 1970
```

**Comment by nacx** [comment]
Interesting. That's because the headers logger logs the [deserialized form](https://github.com/jclouds/jclouds/blob/master/core/src/main/java/org/jclouds/http/HttpUtils.java#L215), not the raw header, and the decoder returns [a date in the past](https://github.com/nacx/jclouds/blob/f5f3fb61801e7b5c3213d2d5e5857ba9cddf0543/core/src/main/java/org/jclouds/io/ContentMetadataCodec.java#L62-L66) according to the spec.

Since it is Azure that is returning the header in an invalid format I think we can close issue but merge this anyway, as it is more tolerant and close to the spec. WDYT?

**Comment by neykov** [comment]
Agree, changes look good. Merging.

**Comment by nacx** [comment]
This should be safe to backport to 2.0.x too. Let's cherry-pick it?

**Comment by neykov** [comment]
Merged into [master](https://git1-us-west.apache.org/repos/asf/jclouds/?p=jclouds.git;a=commit;h=db2f86bcecfe0d68183a166ad07a7f996d332539) and [2.0.x](https://git1-us-west.apache.org/repos/asf/jclouds/?p=jclouds.git;a=commit;h=db4f191b5f8a4d2e77e999f3f6824b2e531bb5e8).

**Comment by nacx** [comment]
I've jsut seen you already did it :) Dismiss the last comment!

**Pull request closed without merging**
