### PR TITLE
Do not test marker contents

### PR DESCRIPTION
**Pull request by andrewgaul**
Some providers like Azure have opaque markers.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@zack-shoylev This commit removes a spurious @DataProvider annotation.  Can you test this on Windows as well?

**Comment by zack-shoylev** [comment]
@andrewgaul I might not be able to test until next week, but will give it a try.

**Comment by zack-shoylev** [comment]
On windows:
```
Tests run: 49, Failures: 1, Errors: 0, Skipped: 5, Time elapsed: 4.947 sec <<< FAILURE! - in TestSuite
testDelimiter(org.jclouds.filesystem.integration.FilesystemContainerIntegrationTest)  Time elapsed: 0.051 sec  <<< FAILURE!
java.lang.AssertionError:
Expecting:
 <"boo\">
to be equal to:
 <"boo/">
but was not.
        at org.jclouds.blobstore.integration.internal.BaseContainerIntegrationTest.testDelimiter(BaseContainerIntegrationTest.java:363)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
        at java.lang.reflect.Method.invoke(Method.java:606)
        at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
        at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
        at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
        at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
        at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
        at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
        at org.testng.TestRunner.privateRun(TestRunner.java:767)
        at org.testng.TestRunner.run(TestRunner.java:617)
        at org.testng.SuiteRunner.runTest(SuiteRunner.java:348)
        at org.testng.SuiteRunner.access$000(SuiteRunner.java:38)
        at org.testng.SuiteRunner$SuiteWorker.run(SuiteRunner.java:382)
        at org.testng.internal.thread.ThreadUtil$2.call(ThreadUtil.java:64)
        at java.util.concurrent.FutureTask.run(FutureTask.java:262)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:744)
```

**Comment by andrewgaul** [comment]
I removed the Windows changes and pushed to master.

**Pull request merged**
