### PR TITLE
Handle lowercase user metadata headers

### PR DESCRIPTION
**Pull request by andrewgaul**
HTTP headers are not case-sensitive.

### CODE REVIEW

**Comment by andrewgaul** [comment]
@kahing @zack-shoylev Please review.

**Comment by kahing** [comment]
:+1:

**Comment by nacx** [comment]
Things like this one are better secured with a test :)

**Comment by zack-shoylev** [comment]
Maybe I am missing something. Shouldn't we be looking specifically for "X-Object-Meta-" in the beginning of the header key?

**Comment by andrewgaul** [comment]
@nacx Not sure the best way to address this -- servers can send any combination of cases.  I encountered jclouds case sensitivity in bouncestorage/swiftproxy#36 but generally https://github.com/bouncestorage/chaos-http-proxy will uncover these kinds of errors.  Some kind of taint or typing seems like a better approach though.

@zack-shoylev Agree that this code is wonky...

**Comment by andrewgaul** [comment]
The original motivation for this pull request has disappeared so I am closing this.  Tightening the check as per @zack-shoylev suggestion requires more work as some code like `getKnowingServerMessesWithMetadataKeyCaseFormat` uses `EntriesWithoutMetaPrefix` to parse headers starting with `X-Account-Meta-`.

**Pull request closed without merging**
